pyconcz_2016/speakers/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from pyconcz_2016.speakers.views import speakers_list, schedule

urlpatterns = [
    url('^$', RedirectView.as_view(pattern_name='speakers_list'), {'type': 'talks'}),
    url('^(?P<type>(talks|workshops))/$', speakers_list, name="speakers_list"),
    url('^schedule/$', schedule, name="speakers_schedule"),
]

pyconcz_2016/sponsors/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from pyconcz_2016.sponsors.views import sponsors_list


urlpatterns = [
    url('^$', sponsors_list, name='sponsors_list'),

    url(r'^offer/$',
        TemplateView.as_view(template_name='pages/sponsors_offer.html'),
        name='sponsors_offer'),
]

pyconcz_2016/team/urls.py
from django.conf.urls import url

from pyconcz_2016.team.views import team_list


urlpatterns = [
    url('^$', team_list, name="team_list"),
]

pyconcz_2016/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView

from pyconcz_2016.common.views import homepage

prefixed_urlpatterns = [
    url(r'^$', homepage, name='homepage'),
    url(r'^announcements/', include('pyconcz_2016.announcements.urls')),
    url(r'^proposals/workshops/$', RedirectView.as_view(url='/2016/proposals/talks')),
    url(r'^proposals/', include('pyconcz_2016.proposals.urls')),

    url(r'^about/team/', include('pyconcz_2016.team.urls')),
    url(r'^speakers/', include('pyconcz_2016.speakers.urls')),
    url(r'^sponsors/', include('pyconcz_2016.sponsors.urls')),

    # static pages
    url(r'^about/$',
        TemplateView.as_view(template_name='pages/about.html'),
        name='about'),
    url(r'^about/code/$',
        TemplateView.as_view(template_name='pages/code.html'),
        name='about_code'),
    url(r'^about/transparency_report/$',
        TemplateView.as_view(template_name='pages/transparency.html'),
        name='about_transparency'),
    url(r'^about/brno/$',
        TemplateView.as_view(template_name='pages/brno.html'),
        name='about_brno'),
]

urlpatterns = (
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
    [
        url(r'^2016/', include(prefixed_urlpatterns)),
        url(r'^admin/', include(admin.site.urls)),
        url(r'^$', RedirectView.as_view(url='/2016/')),
    ]
)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

pyconcz_2016/announcements/models.py
from django.db import models


class Announcement(models.Model):
    message = models.TextField()
    link = models.URLField(blank=True, default='')
    date_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        get_latest_by = 'date_created'
        ordering = ['-date_created']

    def __str__(self):
        if len(self.message) > 30:
            return self.message[:30] + '…'
        else:
            return self.message

pyconcz_2016/speakers/models.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models


class Speaker(models.Model):
    full_name = models.CharField(max_length=200)
    bio = models.TextField()

    keynote = models.BooleanField(default=False, blank=True)

    twitter = models.CharField(max_length=255, blank=True)
    github = models.CharField(max_length=255, blank=True)
    email = models.EmailField()

    photo = models.ImageField(upload_to='speakers/pyconcz2016/')

    talks = models.ManyToManyField(
        'Talk', blank=True, related_name='talks')
    workshops = models.ManyToManyField(
        'Workshop', blank=True, related_name='workshops')

    def __str__(self):
        return self.full_name


class Talk(models.Model):
    DIFFICULTY = (
        ('beginner', 'Beginner'),
        ('advanced', 'Advanced'),
    )

    LANGUAGES = (
        ('en', 'English (preferred)'),
        ('cs', 'Czechoslovak'),
    )

    title = models.CharField(max_length=200)
    abstract = models.TextField()

    language = models.CharField(
        max_length=2, choices=LANGUAGES, default='en'
    )
    difficulty = models.CharField(
        max_length=10, choices=DIFFICULTY, default='beginner',
    )

    def __str__(self):
        return self.title


class Workshop(models.Model):
    DIFFICULTY = (
        ('beginner', 'Beginner'),
        ('advanced', 'Advanced'),
    )

    TYPE = (
        ('workshop', 'Workshop'),
        ('sprint', 'Sprint'),
    )

    LENGTH = (
        ('1h', '1 hour'),
        ('2h', '2 hours'),
        ('2h', '3 hours'),
        ('1d', 'Full day (most sprints go here!)'),
        ('xx', 'Something else! (Please leave a note in the abstract!)')
    )

    LANGUAGES = (
        ('en', 'English (preferred)'),
        ('cs', 'Czech/Slovak'),
    )

    type = models.CharField(
        max_length=10, choices=TYPE, default='sprint'
    )
    title = models.CharField(
        max_length=200, verbose_name='Title'
    )
    abstract = models.TextField()
    language = models.CharField(
        max_length=2, choices=LANGUAGES, default='en'
    )
    difficulty = models.CharField(
        max_length=10, choices=DIFFICULTY, default='beginner',
    )
    length = models.CharField(
        max_length=2, choices=LENGTH, blank=True,
    )

    def __str__(self):
        return self.title


class Slot(models.Model):
    ROOM = (
        ('foyer', 'Foyer'),
        ('d105',  'Main (D105)'),
        ('d0206', 'Right (D0206)'),
        ('d0207', 'Left (D0207)'),

        ('a112', 'A112'),
        ('a113', 'A113'),
    )
    date = models.DateTimeField()

    content_type = models.ForeignKey(
        ContentType, null=True, blank=True, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField(null=True, blank=True)
    content_object = GenericForeignKey('content_type', 'object_id')

    description = models.CharField(max_length=100, blank=True, default='')
    room = models.CharField(max_length=5, choices=ROOM)


class EndTime(models.Func):
    template = 'LAG(date) OVER (PARTITION BY room ORDER BY date DESC)'

    def __init__(self):
        super().__init__(output_field=models.DateTimeField())

    def get_group_by_cols(self):
        return []

pyconcz_2016/sponsors/models.py
from django.db import models


class Sponsor(models.Model):
    LEVEL = (
        (1, 'Platinum'),
        (2, 'Gold'),
        (3, 'Silver'),
        (4, 'Bronze'),
        (5, 'Diversity'),
        (6, 'Media'),
        (7, 'Partners'),
    )

    level = models.PositiveSmallIntegerField(choices=LEVEL, default=3)

    name = models.CharField(max_length=200)
    logo = models.FileField(upload_to='sponsors/pyconcz_2016/')

    description = models.TextField()
    link_url = models.URLField()

    published = models.BooleanField(default=False)

    class Meta:
        ordering = ["level", "name"]

    def __str__(self):
        return self.name

pyconcz_2016/team/models.py
from django.db import models


class Organizer(models.Model):
    full_name = models.CharField(max_length=200)
    email = models.EmailField(
        default='', blank=True,
        help_text="This is private")
    twitter = models.CharField(max_length=255, blank=True)
    github = models.CharField(max_length=255, blank=True)
    photo = models.ImageField(upload_to='team/pyconcz2016/')

    published = models.BooleanField(default=False)

    def __str__(self):
        return self.full_name

pyconcz_2016/announcements/views.py
from django.shortcuts import render
from django.template.response import TemplateResponse

from pyconcz_2016.announcements.models import Announcement


def announcement_list(request):
    items = Announcement.objects.all()
    return TemplateResponse(
        request, 'announcements/archive.html', {'items': items}
    )

pyconcz_2016/common/views.py
from django.template.response import TemplateResponse

from pyconcz_2016.speakers.models import Speaker


def homepage(request):
    keynoters = Speaker.objects.filter(keynote=True)

    return TemplateResponse(
        request, 'pages/homepage.html', {'keynoters': keynoters})

pyconcz_2016/proposals/views.py
from django.forms import modelform_factory
from django.http import Http404
from django.shortcuts import redirect
from django.template import RequestContext
from django.template.response import TemplateResponse
from django.utils.timezone import now

from pyconcz_2016.proposals.config import proposals


def proposal_create(request, *, key):
    try:
        config = proposals.get_config(key)
    except KeyError:
        raise Http404

    context = {'proposal_config': config}

    is_public = not request.user.is_superuser
    right_now = now()
    if is_public and config.date_start > right_now:
        return TemplateResponse(request, 'proposals/proposal_before.html', context)
    elif is_public and config.date_end < right_now:
        return TemplateResponse(request, 'proposals/proposal_after.html', context)

    ProposalForm = modelform_factory(config.model, exclude=['note', 'date'])

    if request.method.lower() == 'post':
        form = ProposalForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            return redirect(to='proposal_success', key=key)

    else:
        form = ProposalForm()

    context['form'] = form
    return TemplateResponse(request, 'proposals/proposal_form.html', context)


def proposal_success(request, *, key):
    context = {'proposal_config_key': key}
    return TemplateResponse(request, 'proposals/proposal_success.html', context)


def proposal_about(request, *, key):
    try:
        config = proposals.get_config(key)
    except KeyError:
        raise Http404

    context = {'proposal_config': config}
    return TemplateResponse(request, config.template_about, context)

pyconcz_2016/speakers/views.py
import datetime
from itertools import chain

from django.db.models import Case
from django.db.models import IntegerField
from django.db.models import Q
from django.db.models import Value
from django.db.models import When
from django.template import RequestContext
from django.template.response import TemplateResponse

from pyconcz_2016.speakers.models import Speaker, Slot, EndTime


def speakers_list(request, type):
    speakers = (Speaker.objects.all()
                .exclude(**{type: None})
                .prefetch_related(type)
                .order_by('full_name'))

    return TemplateResponse(
        request,
        template='speakers/{}_list.html'.format(type),
        context={'speakers': speakers}
    )


def _prefetch_generic(ct):
    if ct == 'talk':
        lookup = {'date__lt': datetime.datetime(year=2016, month=10, day=30)}
    else:
        lookup = {'date__gte': datetime.datetime(year=2016, month=10, day=30)}

    return (
        Slot.objects.all()
        .filter(
            Q(
                content_type__app_label='speakers',
                content_type__model=ct,
            ) | ~Q(description=None),
            **lookup
        )
        .prefetch_related(
            'content_object',
            'content_object__{}s'.format(ct)
        )
        .annotate(
            order=Case(
                When(room='d105', then=Value(1)),
                When(room='d0206', then=Value(2)),
                When(room='d0207', then=Value(3)),
                When(room='a112', then=Value(4)),
                When(room='a113', then=Value(5)),
                default=Value(0),
                output_field=IntegerField()
            ),
            date_end=EndTime()
        )
        .order_by('date', 'order')
    )

def schedule(request):
    slots = chain(
        _prefetch_generic('talk'),
        _prefetch_generic('workshop')
    )

    return TemplateResponse(
        request,
        template='speakers/slot_schedule.html',
        context={
            'slots': slots
        }
    )

pyconcz_2016/sponsors/views.py
from django.template.response import TemplateResponse

from pyconcz_2016.sponsors.models import Sponsor


def sponsors_list(request):
    items = Sponsor.objects.all().filter(published=True)
    return TemplateResponse(request, 'sponsors/sponsors_list.html',
                            {'sponsors_list': items})

pyconcz_2016/team/views.py
from django.template import RequestContext
from django.template.response import TemplateResponse

from pyconcz_2016.team.models import Organizer


def team_list(request):
    organizers = Organizer.objects.all().filter(published=True).order_by('?')

    return TemplateResponse(
        request,
        template='team/organizers_list.html',
        context={
            'organizers': organizers
        }
    )

pyconcz_2016/templates/speakers/base_list.html
{% extends "_base.html" %}

{% block content %}
  <div class="container">
    <h1>{% block speakers_title %}{% endblock %}</h1>

    <ul class="speaker-dir__index">
      <li class="speaker-dir__index__item">Index by first name</li>

      {% for speaker in speakers %}
        {% with speaker.full_name.0 as index_letter %}
          {% ifchanged %}
            <li class="speaker-dir__index__item">
              <a href="#{{ index_letter }}">{{ index_letter|upper }}</a>
            </li>
          {% endifchanged %}
        {% endwith %}
      {% endfor %}
    </ul>

    {% for speaker in speakers %}
      {% with speaker.full_name.0 as index_letter %}
        <section class="speaker">
          <h2 class="speaker__name anchor" {% ifchanged %}id="{{ index_letter }}{% endifchanged %}">
            <a href="#{{ speaker.full_name|slugify }}"
               name="{{ speaker.full_name|slugify }}"
               class="speaker__name__link">
              {{ speaker.full_name }}
            </a>
          </h2>

          <section class="sidebox">
            <div class="portrait">
              <img src="{{ speaker.photo.url }}" alt="{{ speaker.full_name }}" />
            </div>

            <section class="icons">
              {% if speaker.github %}
                <a href="https://github.com/{{ speaker.github }}">
                  <i class="fa fa-fw fa-github-alt" aria-hidden="true"></i> {{ speaker.github }}
                </a>
              {% endif %}
              {% if speaker.twitter %}
                <a href="https://twitter.com/{{ speaker.twitter }}">
                  <i class="fa fa-fw fa-twitter" aria-hidden="true"></i> {{ speaker.twitter }}
                </a>
              {% endif %}
            </section>
          </section>

          <section class="details">
            <p class="bio">{{ speaker.bio|linebreaksbr }}</p>
            {% block speakers_items %}{% endblock %}
          </section>
        </section>
      {% endwith %}
    {% endfor %}
  </div>
{% endblock %}

pyconcz_2016/templates/speakers/slot_schedule.html
{% extends "_base.html" %}
{% load slot_tags %}

{% block content %}
  {% regroup slots by date as slots_by_time %}

  <div class="container timeline">
    {% for slot in slots_by_time %}
      {% ifchanged slot.grouper|date %}
        <h2 class="timeline__day">{{ slot.grouper|date:"l, d F" }}</h2>

          {% if slot.grouper|day_type == 'workshops' %}
            <p>
              Sprints are open whole day along with workshops. All sprints
              will be announced during Saturday.
            </p>
          {% endif %}

          <div class="timeline__header">
            {% if slot.grouper|day_type == 'talks' %}
              <h3 class="timeline__time timeline--header">Time</h3>

              <ul class="timeline__tracks timeline--header">
                <li class="timeline__talk">Room Main (D105)</li>
                <li class="timeline__talk">Room Right (D0206)</li>
                <li class="timeline__talk">Room Left (D0207)</li>
              </ul>
            {% else %}
              <ul class="timeline__tracks timeline--header">
                <li class="timeline__workshop">Room A112</li>
                <li class="timeline__workshop">Room A113</li>
              </ul>
            {% endif %}
          </div>
      {% endifchanged %}

      <div class="timeline__slot {% if slot.list.0.description %}timeline__slot--shared{% endif %}">
        {% if slot.grouper|day_type == 'talks' %}
          <h3 class="timeline__time">{{ slot.grouper|time }}</h3>
        {% endif %}

        {% if slot.list.0.description %}
          <div class="timeline__shared">
            {{ slot.list.0.description }}
          </div>
        {% else %}
          <ul class="timeline__tracks">
            {% if slot.list|length == 1 and not slot.list.0.content_object.talks.all.0.keynote %}
              <li class="timeline__workshop"></li>
            {% endif %}
            {% for talk in slot.list %}
                {% with talk.content_object as event %}
                  {% if talk.content_type.model == 'talk' %}
                  <li class="timeline__talk {% if event.talks.all.0.keynote %}timeline__talk--keynote{% endif %}">
                    <span class="timeline__talk__room">Room {{ talk.get_room_display }}</span>
                    <span class="timeline__talk__title">
                      {% if event.talks.all.0.keynote %}Keynote: {% endif %}
                      {{ event.title }}
                    </span>
                    <span class="timeline__talk__speaker">
                      by
                        {% for speaker in event.talks.all %}
                          <a href="{% url "speakers_list" type="talks" %}#{{ speaker.full_name|slugify }}">{{ speaker }}</a>
                          {% if not forloop.last %} and {% endif %}
                        {% endfor %}
                    </span>
                  </li>
                  {% elif talk.content_type.model == 'workshop' %}
                    <li class="timeline__workshop">
                    {{ talk.date|time }} - {{ talk.date_end|time }}
                    <span class="timeline__workshop__room">Room {{ talk.room|upper }}</span>
                    <span class="timeline__workshop__title">{{ event.title }}</span>
                    <span class="timeline__workshop__speaker">
                      by
                        {% for speaker in event.workshops.all %}
                          <a href="{% url "speakers_list" type="workshops" %}#{{ speaker.full_name|slugify }}">{{ speaker }}</a>
                          {% if not forloop.last %} and {% endif %}
                        {% endfor %}
                    </span>
                    </li>
                  {% else %}
                    {{ talk.description }}
                  {% endif %}
                {% endwith %}
            {% endfor %}
          </ul>
        {% endif %}
      </div>
    {% endfor %}
  </div>
{% endblock %}

pyconcz_2016/templates/speakers/speakers_list.html
{% extends "_base.html" %}

{% block meta_title %}PyCon CZ Speakers{% endblock %}

{% block content %}
  <div class="container">
    {% if show_talks %}
      <h1>Speakers</h1>
    {% endif %}

    {% if show_workshops %}
      <h1>Workshops</h1>
    {% endif %}
  
    {% for speaker in speakers %}
      <section class="speaker">
        <section class="sidebox">
          <img class="portrait" src="{{ speaker.photo.url }}" alt="{{ speaker.full_name }}" />
          <section class="icons">
          {% if speaker.github %}
            <a href="https://github.com/{{ speaker.github }}"><i class="fa fa-fw fa-github-alt" aria-hidden="true"></i></a>
          {% endif %}
          {% if speaker.twitter %}
            <a href="https://twitter.com/{{ speaker.twitter }}"><i class="fa fa-fw fa-twitter" aria-hidden="true"></i></a>
          {% endif %}
          </section>
        </section>

        <section class="details">
          <h2>
            <span class="name">{{ speaker.full_name }}</span><br>
          </h2>

          <p class="bio">{{ speaker.bio|linebreaksbr }}</p>

          {% if show_talks %}
            {% for talk in speaker.talks.all %}
              <span class="talk-title">
              {{ talk.title }}
            </span>
              <p class="talk-description">{{ talk.abstract|linebreaksbr }}</p>
            {% endfor %}
          {% endif %}

          {% if show_workshops %}
            {% for workshop in speaker.workshops.all %}
              <span class="talk-title">
              {{ workshop.title }}
            </span>
              <p class="talk-description">{{ workshop.abstract|linebreaksbr }}</p>
            {% endfor %}
          {% endif %}
        </section>
      </section>
    {% endfor %}
  </div>
{% endblock %}

pyconcz_2016/templates/speakers/speakers_list_base.html
{% extends "_base.html" %}

{% block content %}
  <div class="container">
    <h1>{% block speakers_title %}{% endblock %}</h1>

    {% for speaker in speakers %}
      <section class="speaker">
        <section class="sidebox">
          <img class="portrait" src="{{ speaker.photo.url }}" alt="{{ speaker.full_name }}" />
          <section class="icons">
          {% if speaker.github %}
            <a href="https://github.com/{{ speaker.github }}"><i class="fa fa-fw fa-github-alt" aria-hidden="true"></i></a>
          {% endif %}
          {% if speaker.twitter %}
            <a href="https://twitter.com/{{ speaker.twitter }}"><i class="fa fa-fw fa-twitter" aria-hidden="true"></i></a>
          {% endif %}
          </section>
        </section>

        <section class="details">
          <h2>
            <a name="{{ speaker.full_name|slugify }}" class="name">{{ speaker.full_name }}</a><br>
          </h2>

          <p class="bio">{{ speaker.bio|linebreaksbr }}</p>

          {% block speakers_items %}{% endblock %}
        </section>
      </section>
    {% endfor %}
  </div>
{% endblock %}

pyconcz_2016/templates/speakers/speakers_list_talks.html
{% extends "speakers/speakers_list_base.html" %}

{% block meta_title %}PyCon CZ Speakers{% endblock %}

{% block speakers_title %}Speakers{% endblock %}

{% block speakers_items %}
  {% for talk in speaker.talks.all %}
    <span class="talk-title">
      {{ talk.title }}
    </span>
    <p class="talk-description">{{ talk.abstract|linebreaksbr }}</p>
  {% endfor %}
{% endblock %}

pyconcz_2016/templates/speakers/speakers_list_workshops.html
{% extends "speakers/speakers_list_base.html" %}

{% block meta_title %}PyCon CZ Workshops{% endblock %}

{% block speakers_title %}Workshops{% endblock %}

{% block speakers_items %}
  {% for workshop in speaker.workshops.all %}
    <span class="talk-title">
              {{ workshop.title }}
            </span>
    <p class="talk-description">{{ workshop.abstract|linebreaksbr }}</p>
  {% endfor %}
{% endblock %}

pyconcz_2016/templates/speakers/talks_list.html
{% extends "speakers/base_list.html" %}

{% block meta_title %}PyCon CZ Speakers{% endblock %}

{% block speakers_title %}Speakers{% endblock %}

{% block speakers_items %}
  {% for talk in speaker.talks.all %}
    <span class="talk-title">
      {{ talk.title }}
    </span>
    <p class="talk-description">{{ talk.abstract|linebreaksbr }}</p>
  {% endfor %}
{% endblock %}

pyconcz_2016/templates/speakers/talks_timeline.html
{% extends "_base.html" %}

{% block content %}
  {% regroup talks by date as talks_list %}

  <div class="container timeline">
    {% for slot in talks_list %}
      {% ifchanged slot.grouper|date%}
        <h2 class="timeline__day">{{ slot.grouper|date }}</h2>

        <div class="timeline__header">
          <h3 class="timeline__time timeline--header">Time</h3>
          <ul class="timeline__tracks timeline--header">
            <li class="timeline__talk">Room D105</li>
            <li class="timeline__talk">Room D0206</li>
            <li class="timeline__talk">Room D0207</li>
          </ul>
        </div>

      {% endifchanged %}

      <div class="timeline__slot">
        {% if slot.list|length == 1 %}
          <h3 class="timeline__time">{{ slot.grouper|time }}</h3>

          <div class="timeline__shared">
            {{ slot.list.0.description }}
          </div>
        {% else %}
          <h3 class="timeline__time">{{ slot.grouper|time }}</h3>

          <ul class="timeline__tracks">
            {% for talk in slot.list %}
              <li class="timeline__talk">
                {% if talk.talk.title %}
                  <span class="timeline__talk__room">Room {{ talk.room|upper }}</span>
                  <span class="timeline__talk__title">{{ talk.talk.title }}</span>
                  <span class="timeline__talk__speaker">
                    by
                {% for speaker in talk.talk.speakers.all %}
                  <a href="{% url "speakers_list" type="talks" %}#{{ speaker.full_name|slugify }}">{{ speaker }}</a>{% if not forloop.last %} and {% endif %}
                {% endfor %}
              </span>
                {% else %}
                  {{ talk.description }}
                {% endif %}
              </li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>
    {% endfor %}
  </div>
{% endblock %}

pyconcz_2016/templates/speakers/workshops_list.html
{% extends "speakers/base_list.html" %}

{% block meta_title %}PyCon CZ Workshops{% endblock %}

{% block speakers_title %}Workshops{% endblock %}

{% block speakers_items %}
  {% for workshop in speaker.workshops.all %}
    <span class="talk-title">
              {{ workshop.title }}
            </span>
    <p class="talk-description">{{ workshop.abstract|linebreaksbr }}</p>
  {% endfor %}
{% endblock %}